package com.pluralsight.service.orders;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-18T16:21:33.862+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.pluralsight.com/service/Orders/", name = "Orders")
@XmlSeeAlso({com.pluralsight.schema.order.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Orders {

    @WebMethod(operationName = "ProcessOrderPlacement", action = "http://www.pluralsight.com/service/Orders/ProcessOrderPlacement")
    @WebResult(name = "orderInquiryResponse", targetNamespace = "http://www.pluralsight.com/schema/Order", partName = "orderInquiryResponse")
    public com.pluralsight.schema.order.OrderInquiryResponseType processOrderPlacement(
        @WebParam(partName = "orderInquiry", name = "orderInquiry", targetNamespace = "http://www.pluralsight.com/schema/Order")
        com.pluralsight.schema.order.OrderInquiryType orderInquiry
    );
}
